<div style="font-size:20px; color:pink; margin:20px">
N 次元配列を作成
</div>
<div style="font-size:14px; color:white; margin:20px">
NumPy では、ndarray クラスを用いて、多次元行列を作成することができます。<br>
以下コードでは、2×3 の 2 次元の行列を作成します。<br>
以下コード中の np.int32 は、配列の要素が 32 bit の整数であることを示しています。
</div>

In [30]:
import numpy as np
x = np.array([[1,2,3], [4,5,6]], np.int32)
print(x)

[[1 2 3]
 [4 5 6]]


<div style="font-size:20px; color:pink; margin:20px">
N 次元配列の型・サイズを確認する
</div>
<div style="font-size:14px; color:white; margin:20px">
作成した配列は以下のようにして、型やサイズ（大きさ）を確認できます。
</div>

In [35]:
# 配列自体の型
type(x)

numpy.ndarray

In [32]:
# 配列の要素の型
x.dtype

dtype('int32')

In [33]:
# 配列のサイズ
x.shape

(2, 3)

<div style="font-size:20px; color:pink; margin:20px">
配列の要素にアクセスする
</div>
<div style="font-size:14px; color:white; margin:20px">
他の言語と同じように添字（そえじ）を利用して値を取得
</div>

In [27]:
# 特定の要素にアクセス
x[1,0]
x[1][0]

4

In [28]:
# 0行目のみ
x[0]

array([1, 2, 3], dtype=int32)

In [29]:
# 1行目のみ
x[1]

array([4, 5, 6], dtype=int32)

<div style="font-size:20px; color:pink; margin:20px">
行列 (配列) の要素にアクセスする (インデックスを利用)
</div>
<div style="font-size:14px; color:white; margin:20px">
a[i:j] のように、: (コロン) で区切り、<br>
i 番目の要素 (開始地点) から j 番目の要素 (終了地点) までを切り出して新たな配列を作成できます。<br>
</div>

In [41]:
# 1次元配列を作成
x = np.array([0,1,2,3,4,5,6,7,8,9])
x[2:7]

array([2, 3, 4, 5, 6])

In [42]:
# 後ろから2番目の要素から、前から10番目の要素までを取得
x[-2:10]

array([8, 9])

<div style="font-size:20px; color:pink; margin:20px">
行列 (配列) の要素にアクセスする (数件飛ばしで取得する)
</div>
<div style="font-size:14px; color:white; margin:20px">
a[i:j:k] のように2つの : (コロン) で区切り、<br>
i 番目の要素(開始地点)から j 番目の要素(終了地点)まで、k-1 つスキップしながら取得し、新たな配列を作成できます。<br>
</div>

In [50]:
# 1番目の要素から7番目までの要素まで1つスキップしながら取得
x[1:7:2]

array([1, 3, 5])

In [46]:
# 1番目の要素から7番目までの要素まで2つスキップしながら取得
x[1:7:3]

array([1, 4])

<div style="font-size:20px; color:pink; margin:20px">
行列 (配列) の要素にアクセスする (末尾から指定)
</div>
<div style="font-size:14px; color:white; margin:20px">
a[i:] のように、: (コロン) で区切ると、i 番目の要素から最後までの要素を全て抽出します。
</div>

In [48]:
# 5番目までの要素から最後の要素までを抽出
x[5:]

array([5, 6, 7, 8, 9])

In [53]:
x[:5]

array([0, 1, 2, 3, 4])