<div style="font-size:20px; color:pink; margin:20px">
ベクトルのドット積 (点乗積)
</div>
<div style="font-size:14px; color:white; margin:20px">
ドット積 (a・b) は、np.dot(a, b) で計算できます。<br>
ドット積は、1 次元配列ではベクトルの内積、2 次元配列では行列の積と同じ結果になります。<br>
</div>

In [3]:
import numpy as np

# 整数同士のドット積（通常の掛け算と同じになります）
# 3・4
print(np.dot(3,4))

# 行列同士のドット積
# (2, 3)・(2, 3)
print(np.dot([2,3], [2,3]))

# 複素数を扱うこともできます
# (2j, 3j)・(2j, 3j)
print(np.dot([2j, 3j], [2j, 3j]))

# 2次元行列同士のドット積を計算できます。
a = [[1,0], [0,1]]
b = [[4,1], [2,2]]
print(np.dot(a,b))


12
13
(-13+0j)
[[4 1]
 [2 2]]


<div style="font-size:20px; color:pink; margin:20px">
ベクトルの内積
</div>
<div style="font-size:14px; color:white; margin:20px">
ベクトルの内積 (a・b) は np.inner(a, b) のようにして計算できます。
</div>

In [7]:
# 通常のベクトル同士の内積
# (1, 2, 3)・(0, 1, 0)
a = np.array([1,2,3])
b = np.array([0,1,0])
print(np.inner(a,b))

# 多次元ベクトルの内積を計算
a = np.arange(24).reshape((2,3,4))
print(a)
b = np.arange(4)
print(b)
print(np.inner(a,b))

# b がスカラーの場合は以下のように指定します
a = np.eye(2)
print(a)
print(np.inner(np.eye(2), 7))

2
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[0 1 2 3]
[[ 14  38  62]
 [ 86 110 134]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 7.  0.]
 [ 0.  7.]]


<div style="font-size:20px; color:pink; margin:20px">
ベクトルの外積
</div>
<div style="font-size:14px; color:white; margin:20px">
ベクトルの外積 (a×b) は、np.outer(a, b) のようにして計算できます。
</div>

In [8]:
##マンデルブロット (Mandelbrot)
rl = np.outer(np.ones((5,)), np.linspace(-2,2,5))
print(rl)

im = np.outer(1j*np.linspace(2,-2,5), np.ones((5,)))
print(im)

grid = rl + im
print(grid)

# 文字列をベクトルとして計算することもできます
x = np.array(['a', 'b', 'c'], dtype=object)
print(np.outer(x, [1,2,3]))

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
[[ 0.+2.j  0.+2.j  0.+2.j  0.+2.j  0.+2.j]
 [ 0.+1.j  0.+1.j  0.+1.j  0.+1.j  0.+1.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.-1.j  0.-1.j  0.-1.j  0.-1.j  0.-1.j]
 [ 0.-2.j  0.-2.j  0.-2.j  0.-2.j  0.-2.j]]
[[-2.+2.j -1.+2.j  0.+2.j  1.+2.j  2.+2.j]
 [-2.+1.j -1.+1.j  0.+1.j  1.+1.j  2.+1.j]
 [-2.+0.j -1.+0.j  0.+0.j  1.+0.j  2.+0.j]
 [-2.-1.j -1.-1.j  0.-1.j  1.-1.j  2.-1.j]
 [-2.-2.j -1.-2.j  0.-2.j  1.-2.j  2.-2.j]]
[['a' 'aa' 'aaa']
 ['b' 'bb' 'bbb']
 ['c' 'cc' 'ccc']]
